package fr.formation.entities;
// Generated 29 avr. 2019 17:40:08 by Hibernate Tools 5.1.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Logiciel generated by hbm2java
 */
@Entity
@Table(name = "logiciel", catalog = "debugathor2")
public class Logiciel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idLogiciel;
	private String version;
	private String nomLogiciel;
	private List<Solution> solutions = new ArrayList<Solution>(0);

	public Logiciel() {
	}

	public Logiciel(String nomLogiciel, List<Solution> solutions) {
		this.nomLogiciel = nomLogiciel;
		this.solutions = solutions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idLogiciel", unique = true, nullable = false)
	public Long getIdLogiciel() {
		return this.idLogiciel;
	}

	public void setIdLogiciel(Long idLogiciel) {
		this.idLogiciel = idLogiciel;
	}

	@Column(name = "Version", length = 45)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "NomLogiciel", length = 45)
	public String getNomLogiciel() {
		return this.nomLogiciel;
	}

	public void setNomLogiciel(String nomLogiciel) {
		this.nomLogiciel = nomLogiciel;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "logiciel")
	public List<Solution> getSolutions() {
		return this.solutions;
	}

	public void setSolutions(List<Solution> solutions) {
		this.solutions = solutions;
	}

}
