package fr.formation.entities;
// Generated 15 avr. 2019 13:33:11 by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Logiciel generated by hbm2java
 */
@Entity
@Table(name = "logiciel", catalog = "debugathor")
public class Logiciel implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idLogiciel;
	private String version;
	private String nomLogiciel;
	private Set<Solution> solutions = new HashSet<Solution>(0);

	public Logiciel() {
	}

	public Logiciel(Long idLogiciel) {
		this.idLogiciel = idLogiciel;
	}

	public Logiciel(Long idLogiciel, String nomLogiciel, Set<Solution> solutions) {
		this.idLogiciel = idLogiciel;
		this.nomLogiciel = nomLogiciel;
		this.solutions = solutions;
	}

	@Id

	@Column(name = "idLogiciel", unique = true, nullable = false)
	public Long getIdLogiciel() {
		return this.idLogiciel;
	}

	public void setIdLogiciel(Long idLogiciel) {
		this.idLogiciel = idLogiciel;
	}

	
	@Column(name = "Version", length = 45)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "NomLogiciel", length = 45)
	public String getNomLogiciel() {
		return this.nomLogiciel;
	}

	public void setNomLogiciel(String nomLogiciel) {
		this.nomLogiciel = nomLogiciel;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "logiciel")
	public Set<Solution> getSolutions() {
		return this.solutions;
	}

	public void setSolutions(Set<Solution> solutions) {
		this.solutions = solutions;
	}

}
