package fr.formation.entities;
// Generated 15 avr. 2019 13:33:11 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PropositionId generated by hbm2java
 */
@Embeddable
public class PropositionId implements java.io.Serializable {

	private int utilisateurIdUtilisateur;
	private int solutionIdSolution;

	public PropositionId() {
	}

	public PropositionId(int utilisateurIdUtilisateur, int solutionIdSolution) {
		this.utilisateurIdUtilisateur = utilisateurIdUtilisateur;
		this.solutionIdSolution = solutionIdSolution;
	}

	@Column(name = "utilisateur_IdUtilisateur", nullable = false)
	public int getUtilisateurIdUtilisateur() {
		return this.utilisateurIdUtilisateur;
	}

	public void setUtilisateurIdUtilisateur(int utilisateurIdUtilisateur) {
		this.utilisateurIdUtilisateur = utilisateurIdUtilisateur;
	}

	@Column(name = "solution_idSolution", nullable = false)
	public int getSolutionIdSolution() {
		return this.solutionIdSolution;
	}

	public void setSolutionIdSolution(int solutionIdSolution) {
		this.solutionIdSolution = solutionIdSolution;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PropositionId))
			return false;
		PropositionId castOther = (PropositionId) other;

		return (this.getUtilisateurIdUtilisateur() == castOther.getUtilisateurIdUtilisateur())
				&& (this.getSolutionIdSolution() == castOther.getSolutionIdSolution());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUtilisateurIdUtilisateur();
		result = 37 * result + this.getSolutionIdSolution();
		return result;
	}

}
