package fr.formation.entities;
// Generated 5 avr. 2019 11:02:06 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "debugathor")
public class Utilisateur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idUtilisateur;
	private String mdp;
	private String prenom;
	private String nom;
	private Date dateInsc;
	private String poste;
	private String rang;
	private Set<Solution> solutions = new HashSet<Solution>(0);
	private Set<Proposition> propositions = new HashSet<Proposition>(0);

	public Utilisateur() {
	}

	public Utilisateur(String mdp, String prenom, String nom, Date dateInsc, String poste, String rang) {
		this.mdp = mdp;
		this.prenom = prenom;
		this.nom = nom;
		this.dateInsc = dateInsc;
		this.poste = poste;
		this.rang = rang;
	}

	public Utilisateur(String mdp, String prenom, String nom, Date dateInsc, String poste, String rang,
			Set<Solution> solutions, Set<Proposition> propositions) {
		this.mdp = mdp;
		this.prenom = prenom;
		this.nom = nom;
		this.dateInsc = dateInsc;
		this.poste = poste;
		this.rang = rang;
		this.solutions = solutions;
		this.propositions = propositions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdUtilisateur", unique = true, nullable = false)
	public Integer getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(Integer idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "MDP", nullable = false, length = 45)
	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	@Column(name = "Prenom", nullable = false, length = 45)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "Nom", nullable = false, length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DateInsc", nullable = false, length = 10)
	public Date getDateInsc() {
		return this.dateInsc;
	}

	public void setDateInsc(Date dateInsc) {
		this.dateInsc = dateInsc;
	}

	@Column(name = "Poste", nullable = false, length = 45)
	public String getPoste() {
		return this.poste;
	}

	public void setPoste(String poste) {
		this.poste = poste;
	}

	@Column(name = "Rang", nullable = false, length = 45)
	public String getRang() {
		return this.rang;
	}

	public void setRang(String rang) {
		this.rang = rang;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Solution> getSolutions() {
		return this.solutions;
	}

	public void setSolutions(Set<Solution> solutions) {
		this.solutions = solutions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Proposition> getPropositions() {
		return this.propositions;
	}

	public void setPropositions(Set<Proposition> propositions) {
		this.propositions = propositions;
	}

	@Override
	public String toString() {
		return "Utilisateur [idUtilisateur=" + idUtilisateur + ", mdp=" + mdp + ", prenom=" + prenom + ", nom=" + nom
				+ ", dateInsc=" + dateInsc + ", poste=" + poste + ", rang=" + rang + ", solutions=" + solutions
				+ ", propositions=" + propositions + "]";
	}
	
	

}
